version: '3.8'

services:
  minio:
    image: cdaprod/cda-minio:latest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: "example.com"
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    environment:
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY}
    networks:
      - app_network
    depends_on:
      - minio

volumes:
  minio_data:

networks:
  app_network:
    driver: overlay